// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_CLONE_DRAWING
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_CLONE_DRAWING
void*_Nonnull uniffi_thorn_svg_ffi_fn_clone_drawing(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_FREE_DRAWING
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_FREE_DRAWING
void uniffi_thorn_svg_ffi_fn_free_drawing(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_CONSTRUCTOR_DRAWING_OPEN
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_CONSTRUCTOR_DRAWING_OPEN
void*_Nonnull uniffi_thorn_svg_ffi_fn_constructor_drawing_open(RustBuffer source, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_ADD_ELLIPSE
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_ADD_ELLIPSE
RustBuffer uniffi_thorn_svg_ffi_fn_method_drawing_add_ellipse(void*_Nonnull ptr, RustBuffer bounds, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_ADD_LINE
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_ADD_LINE
RustBuffer uniffi_thorn_svg_ffi_fn_method_drawing_add_line(void*_Nonnull ptr, double x1, double y1, double x2, double y2, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_ADD_RECT
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_ADD_RECT
RustBuffer uniffi_thorn_svg_ffi_fn_method_drawing_add_rect(void*_Nonnull ptr, RustBuffer rect, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_ADD_TEXT
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_ADD_TEXT
RustBuffer uniffi_thorn_svg_ffi_fn_method_drawing_add_text(void*_Nonnull ptr, double x, double y, RustBuffer text, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_BOUNDS
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_BOUNDS
RustBuffer uniffi_thorn_svg_ffi_fn_method_drawing_bounds(void*_Nonnull ptr, RustBuffer id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_CHECK
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_CHECK
RustBuffer uniffi_thorn_svg_ffi_fn_method_drawing_check(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_DELETE
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_DELETE
void uniffi_thorn_svg_ffi_fn_method_drawing_delete(void*_Nonnull ptr, RustBuffer id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_DELETE_ALL
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_DELETE_ALL
void uniffi_thorn_svg_ffi_fn_method_drawing_delete_all(void*_Nonnull ptr, RustBuffer ids, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_GROUP
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_GROUP
RustBuffer uniffi_thorn_svg_ffi_fn_method_drawing_group(void*_Nonnull ptr, RustBuffer ids, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_HIT
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_HIT
RustBuffer uniffi_thorn_svg_ffi_fn_method_drawing_hit(void*_Nonnull ptr, double x, double y, double tolerance, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_MEMBERS
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_MEMBERS
RustBuffer uniffi_thorn_svg_ffi_fn_method_drawing_members(void*_Nonnull ptr, RustBuffer id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_MOVE_ALL
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_MOVE_ALL
void uniffi_thorn_svg_ffi_fn_method_drawing_move_all(void*_Nonnull ptr, RustBuffer ids, double dx, double dy, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_MOVE_BY
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_MOVE_BY
void uniffi_thorn_svg_ffi_fn_method_drawing_move_by(void*_Nonnull ptr, RustBuffer id, double dx, double dy, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_OUTERMOST
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_OUTERMOST
RustBuffer uniffi_thorn_svg_ffi_fn_method_drawing_outermost(void*_Nonnull ptr, RustBuffer id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_REDO
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_REDO
int8_t uniffi_thorn_svg_ffi_fn_method_drawing_redo(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_REORDER
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_REORDER
int8_t uniffi_thorn_svg_ffi_fn_method_drawing_reorder(void*_Nonnull ptr, RustBuffer id, RustBuffer order, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_RESIZE
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_RESIZE
void uniffi_thorn_svg_ffi_fn_method_drawing_resize(void*_Nonnull ptr, RustBuffer id, RustBuffer to, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_SHAPES
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_SHAPES
RustBuffer uniffi_thorn_svg_ffi_fn_method_drawing_shapes(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_SOURCE
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_SOURCE
RustBuffer uniffi_thorn_svg_ffi_fn_method_drawing_source(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_UNDO
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_UNDO
int8_t uniffi_thorn_svg_ffi_fn_method_drawing_undo(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_UNGROUP
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_METHOD_DRAWING_UNGROUP
RustBuffer uniffi_thorn_svg_ffi_fn_method_drawing_ungroup(void*_Nonnull ptr, RustBuffer id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_FUNC_HANDLE_AT
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_FUNC_HANDLE_AT
RustBuffer uniffi_thorn_svg_ffi_fn_func_handle_at(RustBuffer bounds, double x, double y, double tolerance, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_FUNC_HANDLE_DRAG
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_FUNC_HANDLE_DRAG
RustBuffer uniffi_thorn_svg_ffi_fn_func_handle_drag(RustBuffer handle, RustBuffer bounds, double dx, double dy, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_FUNC_HANDLE_POSITION
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_FN_FUNC_HANDLE_POSITION
RustBuffer uniffi_thorn_svg_ffi_fn_func_handle_position(RustBuffer handle, RustBuffer bounds, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUSTBUFFER_ALLOC
RustBuffer ffi_thorn_svg_ffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_thorn_svg_ffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUSTBUFFER_FREE
void ffi_thorn_svg_ffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUSTBUFFER_RESERVE
RustBuffer ffi_thorn_svg_ffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_U8
void ffi_thorn_svg_ffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_U8
void ffi_thorn_svg_ffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_U8
void ffi_thorn_svg_ffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_thorn_svg_ffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_I8
void ffi_thorn_svg_ffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_I8
void ffi_thorn_svg_ffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_I8
void ffi_thorn_svg_ffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_thorn_svg_ffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_U16
void ffi_thorn_svg_ffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_U16
void ffi_thorn_svg_ffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_U16
void ffi_thorn_svg_ffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_thorn_svg_ffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_I16
void ffi_thorn_svg_ffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_I16
void ffi_thorn_svg_ffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_I16
void ffi_thorn_svg_ffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_thorn_svg_ffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_U32
void ffi_thorn_svg_ffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_U32
void ffi_thorn_svg_ffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_U32
void ffi_thorn_svg_ffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_thorn_svg_ffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_I32
void ffi_thorn_svg_ffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_I32
void ffi_thorn_svg_ffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_I32
void ffi_thorn_svg_ffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_thorn_svg_ffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_U64
void ffi_thorn_svg_ffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_U64
void ffi_thorn_svg_ffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_U64
void ffi_thorn_svg_ffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_thorn_svg_ffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_I64
void ffi_thorn_svg_ffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_I64
void ffi_thorn_svg_ffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_I64
void ffi_thorn_svg_ffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_thorn_svg_ffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_F32
void ffi_thorn_svg_ffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_F32
void ffi_thorn_svg_ffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_F32
void ffi_thorn_svg_ffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_F32
float ffi_thorn_svg_ffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_F64
void ffi_thorn_svg_ffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_F64
void ffi_thorn_svg_ffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_F64
void ffi_thorn_svg_ffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_F64
double ffi_thorn_svg_ffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_POINTER
void ffi_thorn_svg_ffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_POINTER
void ffi_thorn_svg_ffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_POINTER
void ffi_thorn_svg_ffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_thorn_svg_ffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_thorn_svg_ffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_thorn_svg_ffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_thorn_svg_ffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_thorn_svg_ffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_POLL_VOID
void ffi_thorn_svg_ffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_CANCEL_VOID
void ffi_thorn_svg_ffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_FREE_VOID
void ffi_thorn_svg_ffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_RUST_FUTURE_COMPLETE_VOID
void ffi_thorn_svg_ffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_FUNC_HANDLE_AT
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_FUNC_HANDLE_AT
uint16_t uniffi_thorn_svg_ffi_checksum_func_handle_at(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_FUNC_HANDLE_DRAG
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_FUNC_HANDLE_DRAG
uint16_t uniffi_thorn_svg_ffi_checksum_func_handle_drag(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_FUNC_HANDLE_POSITION
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_FUNC_HANDLE_POSITION
uint16_t uniffi_thorn_svg_ffi_checksum_func_handle_position(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_ADD_ELLIPSE
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_ADD_ELLIPSE
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_add_ellipse(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_ADD_LINE
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_ADD_LINE
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_add_line(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_ADD_RECT
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_ADD_RECT
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_add_rect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_ADD_TEXT
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_ADD_TEXT
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_add_text(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_BOUNDS
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_BOUNDS
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_bounds(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_CHECK
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_CHECK
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_check(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_DELETE
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_DELETE
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_delete(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_DELETE_ALL
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_DELETE_ALL
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_delete_all(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_GROUP
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_GROUP
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_group(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_HIT
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_HIT
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_hit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_MEMBERS
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_MEMBERS
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_members(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_MOVE_ALL
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_MOVE_ALL
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_move_all(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_MOVE_BY
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_MOVE_BY
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_move_by(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_OUTERMOST
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_OUTERMOST
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_outermost(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_REDO
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_REDO
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_redo(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_REORDER
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_REORDER
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_reorder(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_RESIZE
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_RESIZE
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_resize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_SHAPES
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_SHAPES
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_shapes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_SOURCE
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_SOURCE
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_source(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_UNDO
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_UNDO
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_undo(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_UNGROUP
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_METHOD_DRAWING_UNGROUP
uint16_t uniffi_thorn_svg_ffi_checksum_method_drawing_ungroup(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_CONSTRUCTOR_DRAWING_OPEN
#define UNIFFI_FFIDEF_UNIFFI_THORN_SVG_FFI_CHECKSUM_CONSTRUCTOR_DRAWING_OPEN
uint16_t uniffi_thorn_svg_ffi_checksum_constructor_drawing_open(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_THORN_SVG_FFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_thorn_svg_ffi_uniffi_contract_version(void
    
);
#endif

