// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(thorn_svg_ffiFFI)
import thorn_svg_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_thorn_svg_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_thorn_svg_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * A drawing being edited. See `thorn_svg_core::Drawing`.
 */
public protocol DrawingProtocol : AnyObject {
    
    /**
     * Add an arrow — a line with `data-arrow` saying which ends have a
     * head; returns its `data-id`.
     */
    func addArrow(x1: Double, y1: Double, x2: Double, y2: Double, heads: Heads) throws  -> String
    
    /**
     * Add an ellipse filling `bounds`; returns its `data-id`.
     */
    func addEllipse(bounds: Bounds) throws  -> String
    
    /**
     * Add a line; returns its `data-id`.
     */
    func addLine(x1: Double, y1: Double, x2: Double, y2: Double) throws  -> String
    
    /**
     * Add a rectangle as the topmost shape; returns its `data-id`.
     */
    func addRect(rect: Rect) throws  -> String
    
    /**
     * Add a label anchored at `(x, y)`; returns its `data-id`.
     */
    func addText(x: Double, y: Double, text: String) throws  -> String
    
    /**
     * Bind an end of a `<line>` to a shape, the end put on its edge; or,
     * with no target, unbind it. One undo step.
     */
    func bind(id: String, end: End, target: String?) throws 
    
    /**
     * A shape's extent in the root's user units, through its transform
     * chain; a `<g>`'s is its members'. `None` for an empty group or a
     * shape missing what its kind needs.
     */
    func bounds(id: String)  -> Bounds?
    
    /**
     * Hold the drawing to the profile. Empty means it conforms.
     */
    func check()  -> [Finding]
    
    /**
     * Delete the shape with this `data-id`.
     */
    func delete(id: String) throws 
    
    /**
     * Delete several shapes as one undo step.
     */
    func deleteAll(ids: [String]) throws 
    
    /**
     * Drop an end of a `<line>` at a point: it goes there, bound to the
     * topmost shape within `tolerance` — any but the arrow — or unbound.
     * Returns what it was bound to. One undo step.
     */
    func dropEnd(id: String, end: End, x: Double, y: Double, tolerance: Double) throws  -> String?
    
    /**
     * Where an end of a `<line>` is, in the root's user units; `None`
     * for any other kind.
     */
    func endPoint(id: String, end: End)  -> Point?
    
    /**
     * The face and size a label lays out in, as resvg resolved them —
     * `Helvetica` for a stylesheet's `sans-serif`; with `None`, a new
     * label's. `None` when the label lays out to nothing.
     */
    func font(id: String?)  -> Font?
    
    /**
     * The size a label lays out at, in user units — its `font-size`, or
     * what a stylesheet gave it; with `None`, a new label's.
     */
    func fontSize(id: String?)  -> Double
    
    /**
     * Wrap sibling shapes in a new `<g>`; returns its `data-id`. One undo
     * step.
     */
    func group(ids: [String]) throws  -> String
    
    /**
     * Which ends of a shape have a head, or `None` for a shape that is
     * not an arrow.
     */
    func heads(id: String)  -> Heads?
    
    /**
     * The topmost shape within `tolerance` of the point, in paint order. A
     * member of a group is returned itself; `outermost` names the group.
     */
    func hit(x: Double, y: Double, tolerance: Double)  -> Shape?
    
    /**
     * The shapes directly inside a `<g>`, in paint order.
     */
    func members(id: String)  -> [Shape]
    
    /**
     * Move several shapes by `(dx, dy)` as one undo step.
     */
    func moveAll(ids: [String], dx: Double, dy: Double) throws 
    
    /**
     * Move a shape by `(dx, dy)`.
     */
    func moveBy(id: String, dx: Double, dy: Double) throws 
    
    /**
     * The outermost group a shape is in, or the shape itself.
     */
    func outermost(id: String)  -> Shape?
    
    /**
     * Redo the last undone gesture; `false` when there was nothing to redo.
     */
    func redo() throws  -> Bool
    
    /**
     * Change a shape's place in paint order; `false` when it was already
     * there.
     */
    func reorder(id: String, order: Order) throws  -> Bool
    
    /**
     * Fit a shape to `to`.
     */
    func resize(id: String, to: Bounds) throws 
    
    /**
     * Replace a `<text>`'s characters; plain text, written escaped.
     */
    func setText(id: String, text: String) throws 
    
    /**
     * Wrap a label to `width` user units, its words flowed into `<tspan>`
     * lines; or, with `None`, put them back on one line. One undo step.
     */
    func setWidth(id: String, width: Double?) throws 
    
    /**
     * The shapes, in paint order.
     */
    func shapes()  -> [Shape]
    
    /**
     * The current bytes — what saving writes.
     */
    func source()  -> String
    
    /**
     * Undo the last gesture; `false` when there was nothing to undo.
     */
    func undo() throws  -> Bool
    
    /**
     * Replace a `<g>` with its members, its transform pushed down onto
     * them; returns their ids. One undo step.
     */
    func ungroup(id: String) throws  -> [String]
    
}

/**
 * A drawing being edited. See `thorn_svg_core::Drawing`.
 */
open class Drawing:
    DrawingProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_thorn_svg_ffi_fn_clone_drawing(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_thorn_svg_ffi_fn_free_drawing(pointer, $0) }
    }

    
    /**
     * Open an SVG's text. A `<text>`'s bounds are measured by resvg's
     * layout over the system's fonts — the layout the canvas draws with.
     */
public static func `open`(source: String)throws  -> Drawing {
    return try  FfiConverterTypeDrawing.lift(try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_constructor_drawing_open(
        FfiConverterString.lower(source),$0
    )
})
}
    

    
    /**
     * Add an arrow — a line with `data-arrow` saying which ends have a
     * head; returns its `data-id`.
     */
open func addArrow(x1: Double, y1: Double, x2: Double, y2: Double, heads: Heads)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_add_arrow(self.uniffiClonePointer(),
        FfiConverterDouble.lower(x1),
        FfiConverterDouble.lower(y1),
        FfiConverterDouble.lower(x2),
        FfiConverterDouble.lower(y2),
        FfiConverterTypeHeads.lower(heads),$0
    )
})
}
    
    /**
     * Add an ellipse filling `bounds`; returns its `data-id`.
     */
open func addEllipse(bounds: Bounds)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_add_ellipse(self.uniffiClonePointer(),
        FfiConverterTypeBounds.lower(bounds),$0
    )
})
}
    
    /**
     * Add a line; returns its `data-id`.
     */
open func addLine(x1: Double, y1: Double, x2: Double, y2: Double)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_add_line(self.uniffiClonePointer(),
        FfiConverterDouble.lower(x1),
        FfiConverterDouble.lower(y1),
        FfiConverterDouble.lower(x2),
        FfiConverterDouble.lower(y2),$0
    )
})
}
    
    /**
     * Add a rectangle as the topmost shape; returns its `data-id`.
     */
open func addRect(rect: Rect)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_add_rect(self.uniffiClonePointer(),
        FfiConverterTypeRect.lower(rect),$0
    )
})
}
    
    /**
     * Add a label anchored at `(x, y)`; returns its `data-id`.
     */
open func addText(x: Double, y: Double, text: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_add_text(self.uniffiClonePointer(),
        FfiConverterDouble.lower(x),
        FfiConverterDouble.lower(y),
        FfiConverterString.lower(text),$0
    )
})
}
    
    /**
     * Bind an end of a `<line>` to a shape, the end put on its edge; or,
     * with no target, unbind it. One undo step.
     */
open func bind(id: String, end: End, target: String?)throws  {try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_bind(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterTypeEnd.lower(end),
        FfiConverterOptionString.lower(target),$0
    )
}
}
    
    /**
     * A shape's extent in the root's user units, through its transform
     * chain; a `<g>`'s is its members'. `None` for an empty group or a
     * shape missing what its kind needs.
     */
open func bounds(id: String) -> Bounds? {
    return try!  FfiConverterOptionTypeBounds.lift(try! rustCall() {
    uniffi_thorn_svg_ffi_fn_method_drawing_bounds(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * Hold the drawing to the profile. Empty means it conforms.
     */
open func check() -> [Finding] {
    return try!  FfiConverterSequenceTypeFinding.lift(try! rustCall() {
    uniffi_thorn_svg_ffi_fn_method_drawing_check(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Delete the shape with this `data-id`.
     */
open func delete(id: String)throws  {try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_delete(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
}
}
    
    /**
     * Delete several shapes as one undo step.
     */
open func deleteAll(ids: [String])throws  {try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_delete_all(self.uniffiClonePointer(),
        FfiConverterSequenceString.lower(ids),$0
    )
}
}
    
    /**
     * Drop an end of a `<line>` at a point: it goes there, bound to the
     * topmost shape within `tolerance` — any but the arrow — or unbound.
     * Returns what it was bound to. One undo step.
     */
open func dropEnd(id: String, end: End, x: Double, y: Double, tolerance: Double)throws  -> String? {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_drop_end(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterTypeEnd.lower(end),
        FfiConverterDouble.lower(x),
        FfiConverterDouble.lower(y),
        FfiConverterDouble.lower(tolerance),$0
    )
})
}
    
    /**
     * Where an end of a `<line>` is, in the root's user units; `None`
     * for any other kind.
     */
open func endPoint(id: String, end: End) -> Point? {
    return try!  FfiConverterOptionTypePoint.lift(try! rustCall() {
    uniffi_thorn_svg_ffi_fn_method_drawing_end_point(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterTypeEnd.lower(end),$0
    )
})
}
    
    /**
     * The face and size a label lays out in, as resvg resolved them —
     * `Helvetica` for a stylesheet's `sans-serif`; with `None`, a new
     * label's. `None` when the label lays out to nothing.
     */
open func font(id: String?) -> Font? {
    return try!  FfiConverterOptionTypeFont.lift(try! rustCall() {
    uniffi_thorn_svg_ffi_fn_method_drawing_font(self.uniffiClonePointer(),
        FfiConverterOptionString.lower(id),$0
    )
})
}
    
    /**
     * The size a label lays out at, in user units — its `font-size`, or
     * what a stylesheet gave it; with `None`, a new label's.
     */
open func fontSize(id: String?) -> Double {
    return try!  FfiConverterDouble.lift(try! rustCall() {
    uniffi_thorn_svg_ffi_fn_method_drawing_font_size(self.uniffiClonePointer(),
        FfiConverterOptionString.lower(id),$0
    )
})
}
    
    /**
     * Wrap sibling shapes in a new `<g>`; returns its `data-id`. One undo
     * step.
     */
open func group(ids: [String])throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_group(self.uniffiClonePointer(),
        FfiConverterSequenceString.lower(ids),$0
    )
})
}
    
    /**
     * Which ends of a shape have a head, or `None` for a shape that is
     * not an arrow.
     */
open func heads(id: String) -> Heads? {
    return try!  FfiConverterOptionTypeHeads.lift(try! rustCall() {
    uniffi_thorn_svg_ffi_fn_method_drawing_heads(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * The topmost shape within `tolerance` of the point, in paint order. A
     * member of a group is returned itself; `outermost` names the group.
     */
open func hit(x: Double, y: Double, tolerance: Double) -> Shape? {
    return try!  FfiConverterOptionTypeShape.lift(try! rustCall() {
    uniffi_thorn_svg_ffi_fn_method_drawing_hit(self.uniffiClonePointer(),
        FfiConverterDouble.lower(x),
        FfiConverterDouble.lower(y),
        FfiConverterDouble.lower(tolerance),$0
    )
})
}
    
    /**
     * The shapes directly inside a `<g>`, in paint order.
     */
open func members(id: String) -> [Shape] {
    return try!  FfiConverterSequenceTypeShape.lift(try! rustCall() {
    uniffi_thorn_svg_ffi_fn_method_drawing_members(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * Move several shapes by `(dx, dy)` as one undo step.
     */
open func moveAll(ids: [String], dx: Double, dy: Double)throws  {try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_move_all(self.uniffiClonePointer(),
        FfiConverterSequenceString.lower(ids),
        FfiConverterDouble.lower(dx),
        FfiConverterDouble.lower(dy),$0
    )
}
}
    
    /**
     * Move a shape by `(dx, dy)`.
     */
open func moveBy(id: String, dx: Double, dy: Double)throws  {try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_move_by(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterDouble.lower(dx),
        FfiConverterDouble.lower(dy),$0
    )
}
}
    
    /**
     * The outermost group a shape is in, or the shape itself.
     */
open func outermost(id: String) -> Shape? {
    return try!  FfiConverterOptionTypeShape.lift(try! rustCall() {
    uniffi_thorn_svg_ffi_fn_method_drawing_outermost(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    
    /**
     * Redo the last undone gesture; `false` when there was nothing to redo.
     */
open func redo()throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_redo(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Change a shape's place in paint order; `false` when it was already
     * there.
     */
open func reorder(id: String, order: Order)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_reorder(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterTypeOrder.lower(order),$0
    )
})
}
    
    /**
     * Fit a shape to `to`.
     */
open func resize(id: String, to: Bounds)throws  {try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_resize(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterTypeBounds.lower(to),$0
    )
}
}
    
    /**
     * Replace a `<text>`'s characters; plain text, written escaped.
     */
open func setText(id: String, text: String)throws  {try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_set_text(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterString.lower(text),$0
    )
}
}
    
    /**
     * Wrap a label to `width` user units, its words flowed into `<tspan>`
     * lines; or, with `None`, put them back on one line. One undo step.
     */
open func setWidth(id: String, width: Double?)throws  {try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_set_width(self.uniffiClonePointer(),
        FfiConverterString.lower(id),
        FfiConverterOptionDouble.lower(width),$0
    )
}
}
    
    /**
     * The shapes, in paint order.
     */
open func shapes() -> [Shape] {
    return try!  FfiConverterSequenceTypeShape.lift(try! rustCall() {
    uniffi_thorn_svg_ffi_fn_method_drawing_shapes(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * The current bytes — what saving writes.
     */
open func source() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_thorn_svg_ffi_fn_method_drawing_source(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Undo the last gesture; `false` when there was nothing to undo.
     */
open func undo()throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_undo(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Replace a `<g>` with its members, its transform pushed down onto
     * them; returns their ids. One undo step.
     */
open func ungroup(id: String)throws  -> [String] {
    return try  FfiConverterSequenceString.lift(try rustCallWithError(FfiConverterTypeDrawingError.lift) {
    uniffi_thorn_svg_ffi_fn_method_drawing_ungroup(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDrawing: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Drawing

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Drawing {
        return Drawing(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Drawing) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Drawing {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Drawing, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrawing_lift(_ pointer: UnsafeMutableRawPointer) throws -> Drawing {
    return try FfiConverterTypeDrawing.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDrawing_lower(_ value: Drawing) -> UnsafeMutableRawPointer {
    return FfiConverterTypeDrawing.lower(value)
}


/**
 * One attribute of a shape; a bare attribute has no value.
 */
public struct Attribute {
    public var name: String
    public var value: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, value: String?) {
        self.name = name
        self.value = value
    }
}



extension Attribute: Equatable, Hashable {
    public static func ==(lhs: Attribute, rhs: Attribute) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.value != rhs.value {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAttribute: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Attribute {
        return
            try Attribute(
                name: FfiConverterString.read(from: &buf), 
                value: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Attribute, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterOptionString.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAttribute_lift(_ buf: RustBuffer) throws -> Attribute {
    return try FfiConverterTypeAttribute.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAttribute_lower(_ value: Attribute) -> RustBuffer {
    return FfiConverterTypeAttribute.lower(value)
}


/**
 * Mirrors `thorn_svg_core::Bounds`.
 */
public struct Bounds {
    public var x: Double
    public var y: Double
    public var width: Double
    public var height: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(x: Double, y: Double, width: Double, height: Double) {
        self.x = x
        self.y = y
        self.width = width
        self.height = height
    }
}



extension Bounds: Equatable, Hashable {
    public static func ==(lhs: Bounds, rhs: Bounds) -> Bool {
        if lhs.x != rhs.x {
            return false
        }
        if lhs.y != rhs.y {
            return false
        }
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(x)
        hasher.combine(y)
        hasher.combine(width)
        hasher.combine(height)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBounds: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bounds {
        return
            try Bounds(
                x: FfiConverterDouble.read(from: &buf), 
                y: FfiConverterDouble.read(from: &buf), 
                width: FfiConverterDouble.read(from: &buf), 
                height: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: Bounds, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.x, into: &buf)
        FfiConverterDouble.write(value.y, into: &buf)
        FfiConverterDouble.write(value.width, into: &buf)
        FfiConverterDouble.write(value.height, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBounds_lift(_ buf: RustBuffer) throws -> Bounds {
    return try FfiConverterTypeBounds.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBounds_lower(_ value: Bounds) -> RustBuffer {
    return FfiConverterTypeBounds.lower(value)
}


/**
 * Mirrors `thorn_svg_core::Finding`, with the rule as its one-line text.
 */
public struct Finding {
    public var rule: String
    public var shape: String?
    public var message: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(rule: String, shape: String?, message: String) {
        self.rule = rule
        self.shape = shape
        self.message = message
    }
}



extension Finding: Equatable, Hashable {
    public static func ==(lhs: Finding, rhs: Finding) -> Bool {
        if lhs.rule != rhs.rule {
            return false
        }
        if lhs.shape != rhs.shape {
            return false
        }
        if lhs.message != rhs.message {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(rule)
        hasher.combine(shape)
        hasher.combine(message)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFinding: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Finding {
        return
            try Finding(
                rule: FfiConverterString.read(from: &buf), 
                shape: FfiConverterOptionString.read(from: &buf), 
                message: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Finding, into buf: inout [UInt8]) {
        FfiConverterString.write(value.rule, into: &buf)
        FfiConverterOptionString.write(value.shape, into: &buf)
        FfiConverterString.write(value.message, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFinding_lift(_ buf: RustBuffer) throws -> Finding {
    return try FfiConverterTypeFinding.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFinding_lower(_ value: Finding) -> RustBuffer {
    return FfiConverterTypeFinding.lower(value)
}


/**
 * Mirrors `thorn_svg_core::measure::Font`: the face a label lays out in.
 */
public struct Font {
    public var size: Double
    public var family: String
    public var postScriptName: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(size: Double, family: String, postScriptName: String) {
        self.size = size
        self.family = family
        self.postScriptName = postScriptName
    }
}



extension Font: Equatable, Hashable {
    public static func ==(lhs: Font, rhs: Font) -> Bool {
        if lhs.size != rhs.size {
            return false
        }
        if lhs.family != rhs.family {
            return false
        }
        if lhs.postScriptName != rhs.postScriptName {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(size)
        hasher.combine(family)
        hasher.combine(postScriptName)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFont: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Font {
        return
            try Font(
                size: FfiConverterDouble.read(from: &buf), 
                family: FfiConverterString.read(from: &buf), 
                postScriptName: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Font, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.size, into: &buf)
        FfiConverterString.write(value.family, into: &buf)
        FfiConverterString.write(value.postScriptName, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFont_lift(_ buf: RustBuffer) throws -> Font {
    return try FfiConverterTypeFont.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFont_lower(_ value: Font) -> RustBuffer {
    return FfiConverterTypeFont.lower(value)
}


/**
 * A point in user units.
 */
public struct Point {
    public var x: Double
    public var y: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(x: Double, y: Double) {
        self.x = x
        self.y = y
    }
}



extension Point: Equatable, Hashable {
    public static func ==(lhs: Point, rhs: Point) -> Bool {
        if lhs.x != rhs.x {
            return false
        }
        if lhs.y != rhs.y {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(x)
        hasher.combine(y)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePoint: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Point {
        return
            try Point(
                x: FfiConverterDouble.read(from: &buf), 
                y: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: Point, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.x, into: &buf)
        FfiConverterDouble.write(value.y, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePoint_lift(_ buf: RustBuffer) throws -> Point {
    return try FfiConverterTypePoint.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePoint_lower(_ value: Point) -> RustBuffer {
    return FfiConverterTypePoint.lower(value)
}


/**
 * Mirrors `thorn_svg_core::Rect`.
 */
public struct Rect {
    public var x: Double
    public var y: Double
    public var width: Double
    public var height: Double

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(x: Double, y: Double, width: Double, height: Double) {
        self.x = x
        self.y = y
        self.width = width
        self.height = height
    }
}



extension Rect: Equatable, Hashable {
    public static func ==(lhs: Rect, rhs: Rect) -> Bool {
        if lhs.x != rhs.x {
            return false
        }
        if lhs.y != rhs.y {
            return false
        }
        if lhs.width != rhs.width {
            return false
        }
        if lhs.height != rhs.height {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(x)
        hasher.combine(y)
        hasher.combine(width)
        hasher.combine(height)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRect: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Rect {
        return
            try Rect(
                x: FfiConverterDouble.read(from: &buf), 
                y: FfiConverterDouble.read(from: &buf), 
                width: FfiConverterDouble.read(from: &buf), 
                height: FfiConverterDouble.read(from: &buf)
        )
    }

    public static func write(_ value: Rect, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.x, into: &buf)
        FfiConverterDouble.write(value.y, into: &buf)
        FfiConverterDouble.write(value.width, into: &buf)
        FfiConverterDouble.write(value.height, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRect_lift(_ buf: RustBuffer) throws -> Rect {
    return try FfiConverterTypeRect.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRect_lower(_ value: Rect) -> RustBuffer {
    return FfiConverterTypeRect.lower(value)
}


/**
 * Mirrors `thorn_svg_core::Shape`, minus the node id, which is not stable
 * across edits and has no meaning to a host.
 */
public struct Shape {
    public var kind: ShapeKind
    public var id: String?
    public var group: String?
    public var depth: UInt32
    public var attrs: [Attribute]
    /**
     * A `<text>`'s characters, whitespace collapsed; `None` otherwise.
     */
    public var text: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: ShapeKind, id: String?, group: String?, depth: UInt32, attrs: [Attribute], 
        /**
         * A `<text>`'s characters, whitespace collapsed; `None` otherwise.
         */text: String?) {
        self.kind = kind
        self.id = id
        self.group = group
        self.depth = depth
        self.attrs = attrs
        self.text = text
    }
}



extension Shape: Equatable, Hashable {
    public static func ==(lhs: Shape, rhs: Shape) -> Bool {
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.id != rhs.id {
            return false
        }
        if lhs.group != rhs.group {
            return false
        }
        if lhs.depth != rhs.depth {
            return false
        }
        if lhs.attrs != rhs.attrs {
            return false
        }
        if lhs.text != rhs.text {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(kind)
        hasher.combine(id)
        hasher.combine(group)
        hasher.combine(depth)
        hasher.combine(attrs)
        hasher.combine(text)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeShape: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Shape {
        return
            try Shape(
                kind: FfiConverterTypeShapeKind.read(from: &buf), 
                id: FfiConverterOptionString.read(from: &buf), 
                group: FfiConverterOptionString.read(from: &buf), 
                depth: FfiConverterUInt32.read(from: &buf), 
                attrs: FfiConverterSequenceTypeAttribute.read(from: &buf), 
                text: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Shape, into buf: inout [UInt8]) {
        FfiConverterTypeShapeKind.write(value.kind, into: &buf)
        FfiConverterOptionString.write(value.id, into: &buf)
        FfiConverterOptionString.write(value.group, into: &buf)
        FfiConverterUInt32.write(value.depth, into: &buf)
        FfiConverterSequenceTypeAttribute.write(value.attrs, into: &buf)
        FfiConverterOptionString.write(value.text, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeShape_lift(_ buf: RustBuffer) throws -> Shape {
    return try FfiConverterTypeShape.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeShape_lower(_ value: Shape) -> RustBuffer {
    return FfiConverterTypeShape.lower(value)
}


/**
 * Why an open or a gesture refused; mirrors `thorn_svg_core::Error`.
 */
public enum DrawingError {

    
    
    case Parse(message: String
    )
    case NotSvg
    case NoSuchShape(id: String
    )
    case Unsupported(gesture: String, kind: ShapeKind
    )
    case NotSiblings
    case Edit(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDrawingError: FfiConverterRustBuffer {
    typealias SwiftType = DrawingError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DrawingError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Parse(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .NotSvg
        case 3: return .NoSuchShape(
            id: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Unsupported(
            gesture: try FfiConverterString.read(from: &buf), 
            kind: try FfiConverterTypeShapeKind.read(from: &buf)
            )
        case 5: return .NotSiblings
        case 6: return .Edit(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DrawingError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Parse(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case .NotSvg:
            writeInt(&buf, Int32(2))
        
        
        case let .NoSuchShape(id):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(id, into: &buf)
            
        
        case let .Unsupported(gesture,kind):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(gesture, into: &buf)
            FfiConverterTypeShapeKind.write(kind, into: &buf)
            
        
        case .NotSiblings:
            writeInt(&buf, Int32(5))
        
        
        case let .Edit(message):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


extension DrawingError: Equatable, Hashable {}

extension DrawingError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Mirrors `thorn_svg_core::End`: an end of a `<line>` arrow.
 */

public enum End {
    
    /**
     * `(x1, y1)`, bound by `data-from`.
     */
    case from
    /**
     * `(x2, y2)`, bound by `data-to`.
     */
    case to
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEnd: FfiConverterRustBuffer {
    typealias SwiftType = End

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> End {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .from
        
        case 2: return .to
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: End, into buf: inout [UInt8]) {
        switch value {
        
        
        case .from:
            writeInt(&buf, Int32(1))
        
        
        case .to:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEnd_lift(_ buf: RustBuffer) throws -> End {
    return try FfiConverterTypeEnd.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEnd_lower(_ value: End) -> RustBuffer {
    return FfiConverterTypeEnd.lower(value)
}



extension End: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Mirrors `thorn_svg_core::Handle`.
 */

public enum Handle {
    
    case topLeft
    case top
    case topRight
    case right
    case bottomRight
    case bottom
    case bottomLeft
    case left
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHandle: FfiConverterRustBuffer {
    typealias SwiftType = Handle

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Handle {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .topLeft
        
        case 2: return .top
        
        case 3: return .topRight
        
        case 4: return .right
        
        case 5: return .bottomRight
        
        case 6: return .bottom
        
        case 7: return .bottomLeft
        
        case 8: return .left
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Handle, into buf: inout [UInt8]) {
        switch value {
        
        
        case .topLeft:
            writeInt(&buf, Int32(1))
        
        
        case .top:
            writeInt(&buf, Int32(2))
        
        
        case .topRight:
            writeInt(&buf, Int32(3))
        
        
        case .right:
            writeInt(&buf, Int32(4))
        
        
        case .bottomRight:
            writeInt(&buf, Int32(5))
        
        
        case .bottom:
            writeInt(&buf, Int32(6))
        
        
        case .bottomLeft:
            writeInt(&buf, Int32(7))
        
        
        case .left:
            writeInt(&buf, Int32(8))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandle_lift(_ buf: RustBuffer) throws -> Handle {
    return try FfiConverterTypeHandle.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandle_lower(_ value: Handle) -> RustBuffer {
    return FfiConverterTypeHandle.lower(value)
}



extension Handle: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Mirrors `thorn_svg_core::Heads`: which ends of an arrow have a head.
 */

public enum Heads {
    
    case end
    case start
    case both
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHeads: FfiConverterRustBuffer {
    typealias SwiftType = Heads

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Heads {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .end
        
        case 2: return .start
        
        case 3: return .both
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Heads, into buf: inout [UInt8]) {
        switch value {
        
        
        case .end:
            writeInt(&buf, Int32(1))
        
        
        case .start:
            writeInt(&buf, Int32(2))
        
        
        case .both:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeads_lift(_ buf: RustBuffer) throws -> Heads {
    return try FfiConverterTypeHeads.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHeads_lower(_ value: Heads) -> RustBuffer {
    return FfiConverterTypeHeads.lower(value)
}



extension Heads: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Mirrors `thorn_svg_core::Order`.
 */

public enum Order {
    
    case forward
    case backward
    case toFront
    case toBack
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOrder: FfiConverterRustBuffer {
    typealias SwiftType = Order

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Order {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .forward
        
        case 2: return .backward
        
        case 3: return .toFront
        
        case 4: return .toBack
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Order, into buf: inout [UInt8]) {
        switch value {
        
        
        case .forward:
            writeInt(&buf, Int32(1))
        
        
        case .backward:
            writeInt(&buf, Int32(2))
        
        
        case .toFront:
            writeInt(&buf, Int32(3))
        
        
        case .toBack:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOrder_lift(_ buf: RustBuffer) throws -> Order {
    return try FfiConverterTypeOrder.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOrder_lower(_ value: Order) -> RustBuffer {
    return FfiConverterTypeOrder.lower(value)
}



extension Order: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Mirrors `thorn_svg_core::ShapeKind`.
 */

public enum ShapeKind {
    
    case rect
    case ellipse
    case circle
    case line
    case polyline
    case polygon
    case path
    case text
    case group
    case image
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeShapeKind: FfiConverterRustBuffer {
    typealias SwiftType = ShapeKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ShapeKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .rect
        
        case 2: return .ellipse
        
        case 3: return .circle
        
        case 4: return .line
        
        case 5: return .polyline
        
        case 6: return .polygon
        
        case 7: return .path
        
        case 8: return .text
        
        case 9: return .group
        
        case 10: return .image
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ShapeKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .rect:
            writeInt(&buf, Int32(1))
        
        
        case .ellipse:
            writeInt(&buf, Int32(2))
        
        
        case .circle:
            writeInt(&buf, Int32(3))
        
        
        case .line:
            writeInt(&buf, Int32(4))
        
        
        case .polyline:
            writeInt(&buf, Int32(5))
        
        
        case .polygon:
            writeInt(&buf, Int32(6))
        
        
        case .path:
            writeInt(&buf, Int32(7))
        
        
        case .text:
            writeInt(&buf, Int32(8))
        
        
        case .group:
            writeInt(&buf, Int32(9))
        
        
        case .image:
            writeInt(&buf, Int32(10))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeShapeKind_lift(_ buf: RustBuffer) throws -> ShapeKind {
    return try FfiConverterTypeShapeKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeShapeKind_lower(_ value: ShapeKind) -> RustBuffer {
    return FfiConverterTypeShapeKind.lower(value)
}



extension ShapeKind: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionDouble: FfiConverterRustBuffer {
    typealias SwiftType = Double?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterDouble.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterDouble.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeBounds: FfiConverterRustBuffer {
    typealias SwiftType = Bounds?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeBounds.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeBounds.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFont: FfiConverterRustBuffer {
    typealias SwiftType = Font?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFont.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFont.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypePoint: FfiConverterRustBuffer {
    typealias SwiftType = Point?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypePoint.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypePoint.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeShape: FfiConverterRustBuffer {
    typealias SwiftType = Shape?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeShape.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeShape.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeHandle: FfiConverterRustBuffer {
    typealias SwiftType = Handle?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeHandle.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeHandle.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeHeads: FfiConverterRustBuffer {
    typealias SwiftType = Heads?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeHeads.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeHeads.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeAttribute: FfiConverterRustBuffer {
    typealias SwiftType = [Attribute]

    public static func write(_ value: [Attribute], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeAttribute.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Attribute] {
        let len: Int32 = try readInt(&buf)
        var seq = [Attribute]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeAttribute.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFinding: FfiConverterRustBuffer {
    typealias SwiftType = [Finding]

    public static func write(_ value: [Finding], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFinding.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Finding] {
        let len: Int32 = try readInt(&buf)
        var seq = [Finding]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFinding.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeShape: FfiConverterRustBuffer {
    typealias SwiftType = [Shape]

    public static func write(_ value: [Shape], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeShape.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Shape] {
        let len: Int32 = try readInt(&buf)
        var seq = [Shape]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeShape.read(from: &buf))
        }
        return seq
    }
}
/**
 * The handle of `bounds` within `tolerance` of the point, if any.
 */
public func handleAt(bounds: Bounds, x: Double, y: Double, tolerance: Double) -> Handle? {
    return try!  FfiConverterOptionTypeHandle.lift(try! rustCall() {
    uniffi_thorn_svg_ffi_fn_func_handle_at(
        FfiConverterTypeBounds.lower(bounds),
        FfiConverterDouble.lower(x),
        FfiConverterDouble.lower(y),
        FfiConverterDouble.lower(tolerance),$0
    )
})
}
/**
 * `bounds` after `handle` is dragged by `(dx, dy)`.
 */
public func handleDrag(handle: Handle, bounds: Bounds, dx: Double, dy: Double) -> Bounds {
    return try!  FfiConverterTypeBounds.lift(try! rustCall() {
    uniffi_thorn_svg_ffi_fn_func_handle_drag(
        FfiConverterTypeHandle.lower(handle),
        FfiConverterTypeBounds.lower(bounds),
        FfiConverterDouble.lower(dx),
        FfiConverterDouble.lower(dy),$0
    )
})
}
/**
 * Where a handle sits on a box.
 */
public func handlePosition(handle: Handle, bounds: Bounds) -> Point {
    return try!  FfiConverterTypePoint.lift(try! rustCall() {
    uniffi_thorn_svg_ffi_fn_func_handle_position(
        FfiConverterTypeHandle.lower(handle),
        FfiConverterTypeBounds.lower(bounds),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_thorn_svg_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_func_handle_at() != 7069) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_func_handle_drag() != 52834) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_func_handle_position() != 51884) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_add_arrow() != 7662) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_add_ellipse() != 11165) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_add_line() != 10609) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_add_rect() != 12832) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_add_text() != 58303) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_bind() != 8142) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_bounds() != 7686) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_check() != 12937) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_delete() != 53757) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_delete_all() != 13572) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_drop_end() != 40545) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_end_point() != 45968) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_font() != 674) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_font_size() != 35813) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_group() != 8832) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_heads() != 59389) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_hit() != 61470) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_members() != 17237) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_move_all() != 2740) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_move_by() != 4199) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_outermost() != 20228) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_redo() != 64887) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_reorder() != 50346) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_resize() != 64941) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_set_text() != 35539) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_set_width() != 1447) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_shapes() != 26790) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_source() != 3308) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_undo() != 59527) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_method_drawing_ungroup() != 51363) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_thorn_svg_ffi_checksum_constructor_drawing_open() != 20304) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all